# Site specific settings
title: "IP Testerino"
name: "DYNamyc IP Testerino"
keywords: "IP Provider"
#baseurl: "/testerino"
baseurl: ""
url: "http://website.com"
description: "IP DYN provider"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "es_ES"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: test
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
